# Generated by Django 4.1.4 on 2022-12-28 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('function', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('logic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[('BO', 'Boolean'), ('DT', 'Date/Time'), ('IN', 'Integer'), ('ST', 'String')], max_length=2)),
                ('validation_function', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RuleActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_number', models.PositiveSmallIntegerField()),
                ('parameter_values', models.TextField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.action')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.rule')),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='actions',
            field=models.ManyToManyField(through='rules.RuleActions', to='rules.action'),
        ),
        migrations.AddField(
            model_name='rule',
            name='criteria',
            field=models.ManyToManyField(to='rules.criterion'),
        ),
        migrations.CreateModel(
            name='ActionParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_number', models.PositiveSmallIntegerField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.action')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.parameter')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='parameters',
            field=models.ManyToManyField(through='rules.ActionParameters', to='rules.parameter'),
        ),
    ]
