services:
  db_test:
    image: mysql:8.4.2
    container_name: database_service_test
    volumes:
      - type: bind
        source: ./rules_dump.sql
        target: /docker-entrypoint-initdb.d/rules_dump.sql
        read_only: true
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: rules
      MYSQL_USER_FILE: /run/secrets/db_user_name
      MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
    secrets:
      - db_root_password
      - db_user_password
      - db_user_name
  email_test:
    image: greenmail/standalone:latest
    container_name: email_service_test
    env_file:
      - greenmail.env

  backend_service_test:
    build:
      context: ../../
      dockerfile: backend/engine/Dockerfile
    depends_on:
      - db_test
      - email_test
    ports:
      - 8080:8080
      - 9990:9990
    secrets:
      - db_host
      - db_host_port
      - db_user_password
      - db_user_name
      - engine_reload_key
      - mail_from_address
      - mail_host_port
      - mail_host
      - mail_server_password
      - wildfly_user_name
      - wildfly_user_password

secrets:
  db_host:
    file: ../../secrets/db_host.txt
  db_host_port:
    file: ../../secrets/db_host_port.txt
  db_user_password:
    file: ../../secrets/db_user_password.txt
  db_root_password:
    file: ../../secrets/db_root_password.txt
  db_user_name:
    file: ../../secrets/db_user_name.txt
  engine_reload_key:
    file: ../../secrets/engine_reload_key.txt
  mail_from_address:
    file: ../../secrets/mail_from_address.txt
  mail_host_port:
    file: ../../secrets/mail_host_port.txt
  mail_host:
    file: ../../secrets/mail_host.txt
  mail_server_password:
    file: ../../secrets/mail_server_password.txt
  wildfly_user_name:
    file: ../../secrets/wildfly_user_name.txt
  wildfly_user_password:
    file: ../../secrets/wildfly_user_password.txt
