services:
  backend_service:
    build:
      context: ../../
      dockerfile: backend/engine/Dockerfile
    container_name: engine_service
    networks:
      - rules_engine
    ports:
      - 8080:8080
      - 9990:9990
    volumes:
      - type: bind
        source: ./config/application-demo.properties
        target: /application/config/application.properties

networks:
  rules_engine:
    external: true
