services:
  db:
    image: mysql:8.3.0
    container_name: database_service
    volumes:
      - type: bind
        source: ./rules_dump.sql
        target: /docker-entrypoint-initdb.d/rules_dump.sql
        read_only: true
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: rules
      MYSQL_USER_FILE: /run/secrets/db_user_name
      MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
    secrets:
      - db_root_password
      - db_user_password
      - db_user_name
  email:
    image: axigen/axigen:latest
    container_name: email_service
    ports:
      - 443:443
      - 9443:9443
    volumes:
      - mail-data:/axigen/var
  backend_service:
    build:
      context: ../../
      dockerfile: backend/engine/Dockerfile
    depends_on:
      - db
      - email
    env_file:
      - docker.env
    ports:
      - 8080:8080
      - 9990:9990
    secrets:
      - db_user_password
      - db_user_name

secrets:
  db_user_password:
    file: ../../secrets/db_user_password.txt
  db_root_password:
    file: ../../secrets/db_root_password.txt
  db_user_name:
    file: ../../secrets/db_user_name.txt

volumes:
  mail-data:
    external: true