services:
  backend_service:
    build:
      context: ../../
      dockerfile: backend/engine/Dockerfile
    container_name: engine_service
    env_file:
      - docker.env
    ports:
      - 8080:8080
      - 9990:9990
    secrets:
      - db_user_password
      - db_user_name

secrets:
  db_user_password:
    file: ../../secrets/db_user_password.txt
  db_user_name:
    file: ../../secrets/db_user_name.txt