services:
  django:
    build:
      context: .
    container_name: django_service
    networks:
      - rules_engine
    volumes:
      - django_logs:/app/log
    secrets:
      - engine_host
      - engine_reload_key
      - db_host
      - db_host_port
      - db_user_name
      - db_user_password
      - django_secret_key
      - django_super_user_email
      - django_super_user_name
      - django_super_user_password

  nginx:
    build:
      context: web_server/
    container_name: nginx_service
    networks:
      - rules_engine
    ports:
    - 8000:8000

networks:
  rules_engine:
    external: true

secrets:
  engine_host:
    file: ../secrets/engine_host.txt
  engine_reload_key:
    file: ../secrets/engine_reload_key.txt
  db_host:
    file: ../secrets/db_host.txt
  db_host_port:
    file: ../secrets/db_host_port.txt
  db_user_name:
    file: ../secrets/db_user_name.txt
  db_user_password:
    file: ../secrets/db_user_password.txt
  django_secret_key:
    file: ../secrets/django_secret_key.txt
  django_super_user_email:
    file: ../secrets/django_super_user_email.txt
  django_super_user_name:
    file: ../secrets/django_super_user_name.txt
  django_super_user_password:
    file: ../secrets/django_super_user_password.txt

volumes:
  django_logs: