services:
  django:
    build:
      context: .
    container_name: django_service
    volumes:
      - django_logs:/app/log
    secrets:
      - engine_host
      - engine_reload_key
      - db_host
      - db_user_name
      - db_user_password
      - django_secret_key

  nginx:
    build:
      context: web_server/
    container_name: nginx_service
    ports:
    - 8000:8000

secrets:
  engine_host:
    file: ../secrets/engine_host.txt
  engine_reload_key:
    file: ../secrets/engine_reload_key.txt
  db_host:
    file: ../secrets/db_host.txt
  db_user_name:
    file: ../secrets/db_user_name.txt
  db_user_password:
    file: ../secrets/db_user_password.txt
  django_secret_key:
    file: ../secrets/django_secret_key.txt

volumes:
  django_logs: