# Generated by Django 4.1.7 on 2023-02-28 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('function', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('logic', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Criteria',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[('BO', 'boolean'), ('DA', 'date'), ('DT', 'datetime-local'), ('EM', 'email'), ('NU', 'number'), ('TE', 'tel'), ('TX', 'text'), ('TI', 'time')], max_length=2)),
                ('required', models.BooleanField(default=False)),
                ('help_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive text used to identify this rule, from one to thirty characters in length.', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RuleActionParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_value', models.TextField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.parameter')),
            ],
        ),
        migrations.CreateModel(
            name='RuleActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_number', models.PositiveSmallIntegerField(help_text='Enter a whole number greater than zero.<br>Actions are executed in numerical order, from lowest to highest.')),
                ('action', models.ForeignKey(help_text='Select an action to take when all the criteria above evaluate as true.', on_delete=django.db.models.deletion.CASCADE, to='rules.action')),
                ('parameters', models.ManyToManyField(through='rules.RuleActionParameters', to='rules.parameter')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.rule')),
            ],
        ),
        migrations.AddField(
            model_name='ruleactionparameters',
            name='rule_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.ruleactions'),
        ),
        migrations.AddField(
            model_name='rule',
            name='actions',
            field=models.ManyToManyField(through='rules.RuleActions', to='rules.action'),
        ),
        migrations.AddField(
            model_name='rule',
            name='criteria',
            field=models.ManyToManyField(help_text='Select one or more items.<br>If all of the selected items evaluate as true, the rule is considered applicable and the actions listed below are executed.', to='rules.criterion'),
        ),
        migrations.CreateModel(
            name='ActionParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_number', models.PositiveSmallIntegerField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.action')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.parameter')),
            ],
            options={
                'verbose_name_plural': 'Action Parameters',
            },
        ),
        migrations.AddField(
            model_name='action',
            name='parameters',
            field=models.ManyToManyField(through='rules.ActionParameters', to='rules.parameter'),
        ),
    ]
