# Generated by Django 4.1.7 on 2023-03-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruleactions',
            options={'ordering': ['action_number']},
        ),
        migrations.AlterField(
            model_name='rule',
            name='criteria',
            field=models.ManyToManyField(help_text='Select one or more items.<br> If all of the selected items evaluate as true, the rule is considered applicable and the actions listed below are executed.', to='rules.criterion'),
        ),
    ]
